### ISSUE TITLE
Adapt to `rollups-node:1.1.0`

### ISSUE THREAD

**Issue by endersonmaia** [cartesi/helm-charts#67]
## 📚 Context

rollups-node team is preparing a 1.1.0 release with some breaking changes.

## ✔️ Solution

Adapt the rollups-node-chart. 

## 📈 Subtasks

- [x] Use `PROVIDER_HTTP_ENDPOINT` for advance-runner
- [x] Use `POSTGRES_ENDPOINT` instead of `POSTGRES_*` variables
- [ ] Test using a mounted secret with `.pgpass` file and without `POSTGRES_ENDPOINT`
- [x] Use a single container image release with all service binaries
- [x] `state-server`'s `SF_GENESIS_BLOCK` now receives a decimal (maybe impact our current deployment, but not the cart itself)

## 🎯 Definition of Done

- [ ] CI passing, version bumped to 1.1.0, released to OCI
