### ISSUE TITLE
Adapt to rollups-node:1.3.0

### ISSUE THREAD

**Issue by endersonmaia** [cartesi/helm-charts#76]
## 📚 Context

caretesi/rollups-node:1.3.0 will have a lot of breaking changes.

So we need to plan what are the adjustments needed to support it.

## ✔️ Solution

Create a new helm-chart supporting all the changes that will be available with cartesi/rollups-node:1.3.0

## 📈 Subtasks

- [x] Use a single Pod
- [x] Remove redis chart dependency (redis will be managed by go supervisor)
- [x] Use only environment variables
- [x] Use new compatible rollups-contracts
- [x] ...

## 🎯 Definition of Done

- [x] tests pass for localnode
- [x] tests pass for sepolia

**Comment by omidasadpour** [comment]
Already released and tested successfully !
