### ISSUE TITLE
<title>

### ISSUE THREAD

**Issue by endersonmaia** [cartesi/helm-charts#89]
## 📚 Context

The CI for helm-charts has a kubeconform targeting 3 kubernetes versions, and they're a little "outdated".

We should support the latest 3 kubernetes versions, thatś 1.29, 1.28 and 1.27.

## ✔️ Solution

Update the CI to run kubeconform for the latest 3 kubernetes versions.

## 📈 Subtasks

-   [ ] update kubeconfirm CI
-   [ ] adjust coe to kueconform errors, if any

## 🎯 Definition of Done

-   [ ] CI updated
-   [ ] CI green :heavy_check_mark:
