### ISSUE TITLE
Release rollups-node:1.5.0

### ISSUE THREAD

**Issue by endersonmaia** [cartesi/helm-charts#93]
## 📚 Context
cartesi/rollups-node:1.5.0 was released

https://github.com/cartesi/rollups-node/releases/tag/v1.5.0

## ✔️ Solution

Release `cartesi/rollups-node-chart:1.5.0-0`

## 📈 Subtasks

-   [ ] Update to new version
-   [ ] Update value from config

## 🎯 Definition of Done

-   [ ] A new release was made avilable
